---
- name: Copy kubelet configuration file (11-cgroup.conf)
  template:
    src: 11-cgroup.conf.j2
    dest: /etc/systemd/system/kubelet.service.d/11-cgroup.conf
    owner: root
    group: root
  register: kubelet_cgroup_conf

- name: Restart kubelet service
  systemd:
    name: kubelet
    state: restarted
    daemon_reload: true
  when: kubelet_cgroup_conf.changed

- name: Enable kubelet service
  systemd:
    name: kubelet
    enabled: yes

- name: Start kubelet service
  systemd:
    name: kubelet
    state: started
